camunda.bpm:
  #process-engine-name: ticketbestellung
  rest:
    enabled: true
  admin-user:
    id: ben
    password: ben
    firstName: Benjamin
    lastName: Wolters
spring.datasource.url: jdbc:h2:file:./h2.db
  #filter:
  #  create: All tasks